import type { Config } from "tailwindcss";

const config: Config = {
    content: [
        "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
        "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
        "./src/app/components/**/*.{js,ts,jsx,tsx,mdx}",
    ],
    theme: {
        extend: {
            colors: {
                stake: {
                    bg: "#0A0C10",
                    card: "#111827",
                    "card-inner": "#1E2433",
                    "card-batch": "#1F2937",
                    border: "#374151",
                    "border-subtle": "#1F2937",
                    orange: "#F97316",
                    green: "#22C55E",
                    "green-bg": "#166534",
                    text: "#FFFFFF",
                    "text-secondary": "rgba(255,255,255,0.75)",
                    "text-muted": "#6B7280",
                },
                "outline-variant": "#564334",
                "on-tertiary": "#00344c",
                "secondary": "#c1c6d7",
                "outline": "#a48c7a",
                "secondary-fixed": "#dde2f3",
                "tertiary": "#85cfff",
                "surface-container-highest": "#31353c",
                "tertiary-fixed": "#c7e7ff",
                "on-primary-container": "#623200",
                "surface-tint": "#ffb77d",
                "surface-dim": "#10141a",
                "tertiary-fixed-dim": "#85cfff",
                "tertiary-container": "#00b5fc",
                "inverse-on-surface": "#2d3137",
                "on-tertiary-fixed-variant": "#004c6c",
                "secondary-fixed-dim": "#c1c6d7",
                "inverse-surface": "#dfe2eb",
                "on-secondary-fixed": "#161c27",
                "on-tertiary-fixed": "#001e2e",
                "surface": "#10141a",
                "primary-fixed": "#ffdcc3",
                "on-surface": "#dfe2eb",
                "surface-container-low": "#181c22",
                "on-primary-fixed": "#2f1500",
                "on-error-container": "#ffdad6",
                "surface-variant": "#31353c",
                "surface-bright": "#353940",
                "background": "#10141a",
                "on-secondary": "#2a303d",
                "primary": "#ffb77d",
                "primary-fixed-dim": "#ffb77d",
                "error-container": "#93000a",
                "inverse-primary": "#904d00",
                "surface-container-lowest": "#0a0e14",
                "on-primary-fixed-variant": "#6e3900",
                "on-primary": "#4d2600",
                "surface-container": "#1c2026",
                "on-error": "#690005",
                "surface-container-high": "#262a31",
                "on-secondary-container": "#b3b8c8",
                "on-secondary-fixed-variant": "#414754",
                "on-tertiary-container": "#004360",
                "primary-container": "#ff8c00",
                "error": "#ffb4ab",
                "on-surface-variant": "#ddc1ae",
                "on-background": "#dfe2eb",
                "secondary-container": "#434957"
            },
            fontFamily: {
                sans: ["var(--font-sora)", "Sora", "sans-serif"],
                headline: ["Plus Jakarta Sans", "sans-serif"],
                body: ["Inter", "sans-serif"],
                label: ["Inter", "sans-serif"],
            },
            keyframes: {
                float: {
                    "0%, 100%": { transform: "translateY(0px) rotate(-3deg)" },
                    "50%": { transform: "translateY(-14px) rotate(0deg)" },
                },
                "slide-right": {
                    "0%": { transform: "translateX(-6px)", opacity: "0.7" },
                    "100%": { transform: "translateX(6px)", opacity: "1" },
                },
            },
            animation: {
                float: "float 4s ease-in-out infinite",
                "slide-right": "slide-right 2s ease-in-out infinite alternate",
            },
        },
    },
    plugins: [],
};

export default config;
